### PR TITLE
Fix FirstPartyIsolate and use_case settings.

### LINKED ISSUE #801: [BUG] Cookie counter on subdomains always zero
**Describe the bug**

The cookie counter on websites with a subdomain like `https://en.wikipedia.org/` is always zero, even when there are cookies clearly set and also deleted when leaving the sites.
Manual delete doesn't work as it shows 'No cookies found'.

On sites without a subdomain like `https://github.com/` it works fine.

**To Reproduce**

1. Go to `https://en.wikipedia.org/`
2. Open the addon menu
3. See '0 cookies'
4. Open browser console and go to Storage Inspector

**Expected behavior**

The cookies should get counted properly

**Screenshots**

image

**Your System Info (please complete the following information):**

 - OS: Ubuntu 20.04
 - Browser Info: Firefox 78.0.1
 - CookieAutoDelete Version: latest™ 3.4.0

### PR DESCRIPTION
**Pull request by kennethtran93**
This should fix #801.

In hindsight we should have allowed cookies stored using firstPartyIsolate to be removed even if firstPartyIsolate was (recently) disabled.  This should allow it.

~I'm having some difficulty writing test cases for these so they're not included....for the time being.~  Test Cases Added as of 50da8b4.

### CODE REVIEW

**Comment by kennethtran93** [comment]
/get-build

Test after recent commit for slash-dispatch upgrade.

File: src/services/Libs.ts [hunk 1]
```diff
@@ -151,6 +151,134 @@ export const extractMainDomain = (domain: string): string => {
...
+      msg: 'Libs.getAllCookiesForDomain:  browser.cookies.getAll for domain.',
+      x: {
+        partialTabInfo,
+        domain: hostname,
+        firstPartyDomain: `(${proto},${mainDomain})`,
+      },
+    },
+    debug,
+  );
+  const cookies_fpi_usesite = await browser.cookies.getAll(
```
Comment (ke-d) [inline src/services/Libs.ts]: camelCase for consistency? like `cookiesFPIUsesSite` or something

File: src/services/Libs.ts [hunk 2]
```diff
@@ -151,6 +151,134 @@ export const extractMainDomain = (domain: string): string => {
...
+        msg: 'Libs.getAllCookiesForDomain:  browser.cookies.getAll for domain.',
+        x: {
+          partialTabInfo,
+          domain: hostname,
+          firstPartyDomain: `(${proto},${mainDomain},${siteURL.port})`,
+        },
+      },
+      debug,
+    );
+    const cookies_fpi_usesite_port = await browser.cookies.getAll(
```
Comment (ke-d) [inline src/services/Libs.ts]: Same as above.

**Review by ke-d — DISMISSED** [review]

File: src/services/Libs.ts (hunk 1 above)
Comment (kennethtran93) [reply src/services/Libs.ts]: Resolved in 
097c8cf

File: src/services/Libs.ts (hunk 2 above)
Comment (kennethtran93) [reply src/services/Libs.ts]: Resolved in 
097c8cf
